### ISSUE TITLE
Whitespace around comments handled different from lessc

### ISSUE THREAD

**Issue by InconceivableVizzini** [assemble/assemble-less#12]
assemble-less is handling whitespace/newlines around comments differently than lessc (lessc leaves the newlines, assemble-less is removing them).

Obviously this isn't a major problem but it does cause a nuisance with any commited css files.

eg,

```
/* blah
****/
/* blah
****/
```

vs

```
/* blah
****/

/* blah
****/
```

**Comment by jonschlinkert** [comment]
This is more likely due to changes in Less.js since the task doesn't modify whitespace or formatting in any way. Did you try comparing the output of different versions of Less.js? 

e.g:

``` js
less: {
  options: {
    version: "less-1.4.0"
  }
}
```

You would need to install each version you wanted to test, and then specify the path to the version you want to use in the task options.

**Comment by jonschlinkert** [comment]
ping @InconceivableVizzini
