### ISSUE TITLE
Error : Warning: Task "less" not found. Use --force to continue.

### ISSUE THREAD

**Issue by ethyde** [assemble/assemble-less#28]
Hi,
I try to use this plugin for a project, I run the task with `grunt less` but i have the error "Warning: Task "less" not found. Use --force to continue.". grunt-contrib-less work perfectly but i need @import options. Can you help me ? 

My grunt task is : 

```
less: {
    options: {
        paths: 'assets/css',
        imports: {
            less: ['normalize.css']
        }
    },
    files: {
        src:'<%= meta.files.less %>/base.less',
        dest: '<%= meta.files.destAssets %>/css/base.css'
    }
}
```

Thanks for all and sorry for my bad english.

**Comment by jonschlinkert** [comment]
Sounds like the task isn't being loaded. Are you using something like load-grunt-tasks? If so, it will only load tasks with the name `grunt`, so you have to add it to the gruntfile. e.g 

``` js
grunt.loadNpmTasks('assemble-less');
```

**Comment by ethyde** [comment]
Ok, it's work ! :)
But now i have the following error with `assemble-less` : "Warning: An error occurred while processing a template (Cannot read property 'dest' of undefined). Use --force to continue" but not with `grunt-contrib-less`

**Comment by jonschlinkert** [comment]
It sounds like a lodash template issue. something in your config is defined wrong. Do a search for `.dest` in the gruntfile (and any config files that you have, e.g. `grunt.file.readJSON('foo.json')`), you might see the inconsistency. 

If you can't find it, try using real filepaths for dest values, instead of config templates until you find which one is causing it. (e.g. do `foo/bar/*.html` instead of `<%= foo.bar %>/*.html`.

**Comment by ethyde** [comment]
All right Thanks for all ! :)

**Comment by jonschlinkert** [comment]
no prob!
