### ISSUE TITLE
Read in data from template YAML headers to load in the needed LESS files

### ISSUE THREAD

**Issue by jonschlinkert** [assemble/assemble-less#3]
This feature would allow dynamic building of components in Assemble

**Comment by doowb** [comment]
I don't think this issue should be addressed in this plugin. I think Assemble would read in the YAML headers and create the configuration options for the assemble-less library to build the less/css components correctly.

There should be a new issue for splitting out the assemble-less library so it can be called from other libraries instead of just from the plugin.

**Comment by doowb** [comment]
Created #5 for moving the logic into a new library to address this issue.

**Comment by jonschlinkert** [comment]
:+1:
